#!/usr/bin/env python3
"""Check sliced CSI .dat windows against slice/sync indexes and review notes."""

from __future__ import annotations

import argparse
import csv
import math
import re
import struct
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path

import numpy as np


HEADER_SIZE = 272

OUT_FIELDS = [
    "sample_id",
    "session_id",
    "person_id",
    "environment_id",
    "action_id",
    "trial_id",
    "csi_out_path",
    "csi_in_path",
    "sync_status",
    "sync_quality_flags",
    "slice_status",
    "csi_index_method",
    "expected_packets_slice_index",
    "written_packets_slice_index",
    "expected_packets_sync_index",
    "dat_packet_count",
    "packet_count_delta_slice",
    "packet_count_delta_sync",
    "action_duration_sec",
    "packet_rate_hz",
    "file_size_bytes",
    "parse_status",
    "bad_packet_count",
    "trailing_partial_packet_count",
    "csi_size_mismatch_count",
    "bad_csi_size_count",
    "payload_packets_checked",
    "zero_packet_count",
    "num_rx_values",
    "num_tx_values",
    "num_subcarrier_values",
    "global_nonzero_ratio",
    "global_amp_min",
    "global_amp_mean",
    "global_amp_std",
    "global_amp_max",
    "dead_link_count",
    "link_nonzero_ratio_min",
    "link_amp_mean_min",
    "video_review_issue_count",
    "video_review_categories",
    "video_review_resample_statuses",
    "video_review_descriptions",
    "quality_flags",
    "final_status",
    "notes",
]

OUTLIER_FIELDS = [
    "sample_id",
    "session_id",
    "action_id",
    "trial_id",
    "final_status",
    "quality_flags",
    "dat_packet_count",
    "packet_rate_hz",
    "global_nonzero_ratio",
    "global_amp_mean",
    "video_review_categories",
    "video_review_resample_statuses",
    "csi_out_path",
    "notes",
]

EXCLUDE_FLAGS = {
    "missing_csi_slice_file",
    "empty_csi_slice_file",
    "no_dat_packets",
    "bad_csi_size",
    "csi_size_mismatch",
    "trailing_partial_packet",
    "packet_count_mismatch_slice_index",
    "packet_count_mismatch_sync_index",
    "all_zero_csi_payload",
    "dead_rx_tx_link",
    "video_review_issue",
    "slice_status_not_ok",
}


@dataclass(frozen=True)
class VideoReviewRule:
    session_id: str
    clip_expr: str
    category: str
    description: str
    resample_status: str
    match_kind: str
    exact_ids: frozenset[str] = frozenset()
    prefix: str = ""
    start_trial: int | None = None
    end_trial: int | None = None

    def matches(self, sample_id: str) -> bool:
        if self.match_kind == "exact":
            return sample_id in self.exact_ids
        if self.match_kind == "wildcard":
            return sample_id.startswith(self.prefix)
        if self.match_kind == "from_trial":
            return self._trial_matches(sample_id, upper_bound=None)
        if self.match_kind == "range":
            return sample_id in self.exact_ids or self._trial_matches(sample_id, upper_bound=self.end_trial)
        return False

    def _trial_matches(self, sample_id: str, upper_bound: int | None) -> bool:
        if self.start_trial is None or not self.prefix:
            return False
        if not sample_id.startswith(self.prefix):
            return False
        suffix = sample_id[len(self.prefix) :]
        if not re.fullmatch(r"\d{3}", suffix):
            return False
        trial = int(suffix)
        if trial < self.start_trial:
            return False
        if upper_bound is not None and trial > upper_bound:
            return False
        return True


@dataclass
class DatQuality:
    parse_status: str
    packet_count: int = 0
    file_size_bytes: int = 0
    bad_packet_count: int = 0
    trailing_partial_packet_count: int = 0
    csi_size_mismatch_count: int = 0
    bad_csi_size_count: int = 0
    payload_packets_checked: int = 0
    zero_packet_count: int = 0
    num_rx_values: str = ""
    num_tx_values: str = ""
    num_subcarrier_values: str = ""
    global_nonzero_ratio: float = math.nan
    global_amp_min: float = math.nan
    global_amp_mean: float = math.nan
    global_amp_std: float = math.nan
    global_amp_max: float = math.nan
    dead_link_count: int = 0
    link_nonzero_ratio_min: float = math.nan
    link_amp_mean_min: float = math.nan
    notes: str = ""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", default=".", help="Workspace root.")
    parser.add_argument(
        "--slice-index",
        default="sliced_windows_by_session/slice_index.csv",
        help="CSV generated by data_processing/slice_csi_video_windows.py.",
    )
    parser.add_argument(
        "--sync-index",
        default="quality_report_deep/csi_video_sync_index/csi_video_sync_index.csv",
        help="CSV generated by data_processing/build_csi_video_sync_index.py.",
    )
    parser.add_argument(
        "--video-review",
        default="quality_report_deep/Video_review.md",
        help="Manual video review markdown. Use empty string to skip.",
    )
    parser.add_argument(
        "--output-dir",
        default="quality_report_deep/csi_slice_quality",
        help="Directory for generated CSV and Markdown reports.",
    )
    parser.add_argument("--session", action="append", default=[], help="Filter by session_id. Can be repeated.")
    parser.add_argument("--action", action="append", default=[], help="Filter by action_id. Can be repeated.")
    parser.add_argument("--sample-id", action="append", default=[], help="Filter by sample_id. Can be repeated.")
    parser.add_argument("--limit", type=int, default=None, help="Maximum number of selected rows.")
    parser.add_argument(
        "--payload-sample-packets",
        type=int,
        default=32,
        help="Number of valid packets per .dat file to parse for CSI payload stats. Use 0 for header-only.",
    )
    parser.add_argument("--packet-rate-low-hz", type=float, default=80.0)
    parser.add_argument("--packet-rate-high-hz", type=float, default=130.0)
    parser.add_argument("--target-csi-rate-hz", type=float, default=100.0)
    parser.add_argument("--low-nonzero-ratio", type=float, default=0.95)
    parser.add_argument("--constant-amp-std", type=float, default=1e-6)
    parser.add_argument("--quiet", action="store_true", help="Disable terminal progress output.")
    return parser.parse_args()


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def write_csv(path: Path, rows: list[dict[str, object]], fields: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, "") for field in fields})


def to_int(value: object) -> int | None:
    try:
        if value is None or value == "":
            return None
        return int(float(str(value)))
    except ValueError:
        return None


def to_float(value: object) -> float | None:
    try:
        if value is None or value == "":
            return None
        number = float(str(value))
    except ValueError:
        return None
    return number if math.isfinite(number) else None


def fmt_float(value: float | int | None, digits: int = 6) -> str:
    if value is None:
        return ""
    try:
        number = float(value)
    except (TypeError, ValueError):
        return ""
    if not math.isfinite(number):
        return ""
    return f"{number:.{digits}f}"


def rel(path: Path | None, root: Path) -> str:
    if path is None:
        return ""
    try:
        return str(path.resolve().relative_to(root.resolve()))
    except ValueError:
        return str(path)


def resolve_path(root: Path, value: str) -> Path:
    path = Path(value)
    if not path.is_absolute():
        path = root / path
    return path


def clean_markdown_cell(value: str) -> str:
    value = value.strip()
    value = value.replace("**", "")
    return value.strip()


def extract_code_cell(value: str) -> str:
    match = re.search(r"`([^`]+)`", value)
    if match:
        return match.group(1).strip()
    return clean_markdown_cell(value)


def make_video_review_rule(
    session_id: str,
    clip_expr: str,
    category: str,
    description: str,
    resample_status: str,
) -> VideoReviewRule:
    expr = clip_expr.replace("–", "-").replace("—", "-").strip()
    expr = re.sub(r"\s+", " ", expr)

    if "*" in expr:
        return VideoReviewRule(
            session_id=session_id,
            clip_expr=clip_expr,
            category=category,
            description=description,
            resample_status=resample_status,
            match_kind="wildcard",
            prefix=expr.split("*", 1)[0],
        )

    from_match = re.fullmatch(r"(.+_R)(\d{3})\s*之后", expr)
    if from_match:
        return VideoReviewRule(
            session_id=session_id,
            clip_expr=clip_expr,
            category=category,
            description=description,
            resample_status=resample_status,
            match_kind="from_trial",
            prefix=from_match.group(1),
            start_trial=int(from_match.group(2)),
        )

    range_match = re.fullmatch(r"(.+_R)(\d{3})-(\d{3})", expr)
    if range_match:
        prefix = range_match.group(1)
        start_trial = int(range_match.group(2))
        end_trial = int(range_match.group(3))
        exact_ids = frozenset(f"{prefix}{trial:03d}" for trial in range(start_trial, end_trial + 1))
        return VideoReviewRule(
            session_id=session_id,
            clip_expr=clip_expr,
            category=category,
            description=description,
            resample_status=resample_status,
            match_kind="range",
            exact_ids=exact_ids,
            prefix=prefix,
            start_trial=start_trial,
            end_trial=end_trial,
        )

    return VideoReviewRule(
        session_id=session_id,
        clip_expr=clip_expr,
        category=category,
        description=description,
        resample_status=resample_status,
        match_kind="exact",
        exact_ids=frozenset({expr}),
    )


def parse_video_review_rules(markdown_text: str) -> list[VideoReviewRule]:
    rules: list[VideoReviewRule] = []
    in_detail_table = False
    saw_detail_heading = False

    for raw_line in markdown_text.splitlines():
        line = raw_line.strip()
        if line.startswith("## 详细问题清单"):
            in_detail_table = True
            saw_detail_heading = True
            continue
        if in_detail_table and line.startswith("## "):
            break
        if saw_detail_heading and not in_detail_table:
            continue
        if not line.startswith("|") or "`" not in line:
            continue

        cells = [cell.strip() for cell in line.strip("|").split("|")]
        if len(cells) < 6 or cells[0].strip() in {"#", ":-:"}:
            continue

        session_id = clean_markdown_cell(cells[1])
        clip_expr = extract_code_cell(cells[2])
        category = clean_markdown_cell(cells[3])
        description = clean_markdown_cell(cells[4])
        resample_status = clean_markdown_cell(cells[5])
        if not session_id or not clip_expr:
            continue
        rules.append(make_video_review_rule(session_id, clip_expr, category, description, resample_status))

    return rules


def parse_csi_payload(payload: bytes, num_rx: int, num_tx: int, num_subcarriers: int) -> np.ndarray:
    expected_values = 2 * num_rx * num_tx * num_subcarriers
    raw = np.frombuffer(payload, dtype="<i2")
    if raw.size != expected_values:
        raise ValueError(f"payload value count mismatch: got={raw.size}, expected={expected_values}")
    raw = raw.reshape(num_rx, num_tx, num_subcarriers, 2)
    real = raw[..., 0].astype(np.float32)
    imag = raw[..., 1].astype(np.float32)
    csi = real + 1j * imag
    return np.transpose(csi, (2, 0, 1))


def read_dat_quality(path: Path, payload_sample_packets: int = 32) -> DatQuality:
    file_size = path.stat().st_size
    if file_size == 0:
        return DatQuality(parse_status="empty", file_size_bytes=0, notes="empty file")

    packet_count = 0
    bad_packet_count = 0
    trailing_partial_packet_count = 0
    csi_size_mismatch_count = 0
    bad_csi_size_count = 0
    payload_packets_checked = 0
    zero_packet_count = 0
    stopped_on_partial = False
    notes: list[str] = []

    rx_values: Counter[int] = Counter()
    tx_values: Counter[int] = Counter()
    subcarrier_values: Counter[int] = Counter()

    total_values = 0
    nonzero_values = 0
    amp_sum = 0.0
    amp_sq_sum = 0.0
    amp_min: float | None = None
    amp_max: float | None = None
    link_total: defaultdict[tuple[int, int], int] = defaultdict(int)
    link_nonzero: defaultdict[tuple[int, int], int] = defaultdict(int)
    link_amp_sum: defaultdict[tuple[int, int], float] = defaultdict(float)

    with path.open("rb") as f:
        offset = 0
        while offset + HEADER_SIZE <= file_size:
            f.seek(offset)
            header = f.read(HEADER_SIZE)
            if len(header) < HEADER_SIZE:
                trailing_partial_packet_count += 1
                bad_packet_count += 1
                stopped_on_partial = True
                break

            csi_size = struct.unpack_from("<I", header, 0)[0]
            num_rx = header[46]
            num_tx = header[47]
            num_subcarriers = struct.unpack_from("<I", header, 52)[0]
            rx_values[num_rx] += 1
            tx_values[num_tx] += 1
            subcarrier_values[num_subcarriers] += 1

            if csi_size <= 0:
                bad_csi_size_count += 1
                bad_packet_count += 1
                notes.append(f"bad csi_size at offset {offset}")
                break

            next_offset = offset + HEADER_SIZE + csi_size
            if next_offset > file_size:
                trailing_partial_packet_count += 1
                bad_packet_count += 1
                stopped_on_partial = True
                break

            expected_size = 4 * num_rx * num_tx * num_subcarriers
            if csi_size != expected_size:
                csi_size_mismatch_count += 1
                bad_packet_count += 1
            else:
                packet_count += 1
                if payload_packets_checked < payload_sample_packets:
                    payload = f.read(csi_size)
                    try:
                        csi = parse_csi_payload(payload, num_rx, num_tx, num_subcarriers)
                    except ValueError as exc:
                        bad_packet_count += 1
                        notes.append(str(exc))
                    else:
                        payload_packets_checked += 1
                        amp = np.abs(csi)
                        packet_nonzero = int(np.count_nonzero(csi))
                        packet_total = int(csi.size)
                        if packet_nonzero == 0:
                            zero_packet_count += 1

                        total_values += packet_total
                        nonzero_values += packet_nonzero
                        amp_sum += float(np.sum(amp))
                        amp_sq_sum += float(np.sum(amp**2))
                        cur_min = float(np.min(amp))
                        cur_max = float(np.max(amp))
                        amp_min = cur_min if amp_min is None else min(amp_min, cur_min)
                        amp_max = cur_max if amp_max is None else max(amp_max, cur_max)

                        for rx in range(num_rx):
                            for tx in range(num_tx):
                                link = (rx, tx)
                                values = csi[:, rx, tx]
                                link_total[link] += int(values.size)
                                link_nonzero[link] += int(np.count_nonzero(values))
                                link_amp_sum[link] += float(np.sum(np.abs(values)))

            offset = next_offset

        if offset < file_size and not stopped_on_partial:
            trailing_partial_packet_count += 1
            bad_packet_count += 1

    if packet_count == 0:
        parse_status = "empty" if file_size == 0 else "error"
    elif bad_packet_count:
        parse_status = "warn"
    else:
        parse_status = "ok"

    if total_values:
        global_nonzero_ratio = nonzero_values / total_values
        global_amp_mean = amp_sum / total_values
        global_amp_var = amp_sq_sum / total_values - global_amp_mean**2
        global_amp_std = math.sqrt(max(global_amp_var, 0.0))
    else:
        global_nonzero_ratio = math.nan
        global_amp_mean = math.nan
        global_amp_std = math.nan

    link_ratios = []
    link_amp_means = []
    for link, total in link_total.items():
        if total <= 0:
            continue
        link_ratios.append(link_nonzero[link] / total)
        link_amp_means.append(link_amp_sum[link] / total)
    dead_link_count = sum(1 for ratio in link_ratios if ratio == 0.0)

    return DatQuality(
        parse_status=parse_status,
        packet_count=packet_count,
        file_size_bytes=file_size,
        bad_packet_count=bad_packet_count,
        trailing_partial_packet_count=trailing_partial_packet_count,
        csi_size_mismatch_count=csi_size_mismatch_count,
        bad_csi_size_count=bad_csi_size_count,
        payload_packets_checked=payload_packets_checked,
        zero_packet_count=zero_packet_count,
        num_rx_values=";".join(str(value) for value in sorted(rx_values)),
        num_tx_values=";".join(str(value) for value in sorted(tx_values)),
        num_subcarrier_values=";".join(str(value) for value in sorted(subcarrier_values)),
        global_nonzero_ratio=global_nonzero_ratio,
        global_amp_min=amp_min if amp_min is not None else math.nan,
        global_amp_mean=global_amp_mean,
        global_amp_std=global_amp_std,
        global_amp_max=amp_max if amp_max is not None else math.nan,
        dead_link_count=dead_link_count,
        link_nonzero_ratio_min=min(link_ratios) if link_ratios else math.nan,
        link_amp_mean_min=min(link_amp_means) if link_amp_means else math.nan,
        notes="; ".join(notes),
    )


def classify_packet_rate(
    packet_count: int | None,
    action_duration_sec: float | None,
    low_hz: float,
    high_hz: float,
) -> list[str]:
    if packet_count is None or action_duration_sec is None or action_duration_sec <= 0:
        return ["missing_packet_rate"]
    rate = packet_count / action_duration_sec
    if rate < low_hz:
        return ["low_packet_rate"]
    if rate > high_hz:
        return ["high_packet_rate"]
    return []


def final_status_from_flags(flags: list[str]) -> str:
    if any(flag in EXCLUDE_FLAGS for flag in flags):
        return "exclude"
    if flags:
        return "warn"
    return "ok"


def select_rows(rows: list[dict[str, str]], args: argparse.Namespace) -> list[dict[str, str]]:
    sessions = set(args.session)
    actions = set(args.action)
    sample_ids = set(args.sample_id)
    selected = []
    for row in rows:
        if sessions and row.get("session_id") not in sessions:
            continue
        if actions and row.get("action_id") not in actions:
            continue
        if sample_ids and row.get("sample_id") not in sample_ids:
            continue
        selected.append(row)
    if args.limit is not None:
        selected = selected[: args.limit]
    return selected


def matching_review_rules(sample_id: str, rules: list[VideoReviewRule]) -> list[VideoReviewRule]:
    return [rule for rule in rules if rule.matches(sample_id)]


def build_quality_row(
    root: Path,
    slice_row: dict[str, str],
    sync_row: dict[str, str] | None,
    review_rules: list[VideoReviewRule],
    args: argparse.Namespace,
) -> dict[str, object]:
    sample_id = slice_row.get("sample_id", "")
    csi_out_value = slice_row.get("csi_out_path", "")
    csi_path = resolve_path(root, csi_out_value) if csi_out_value else root / "__missing_csi_out_path__"
    flags: list[str] = []
    notes: list[str] = []

    expected_slice = to_int(slice_row.get("csi_packets_expected"))
    written_slice = to_int(slice_row.get("csi_packets_written"))
    expected_sync = to_int(sync_row.get("csi_action_packet_count")) if sync_row else None
    action_duration_sec = to_float(sync_row.get("action_duration_sec")) if sync_row else None
    packet_rate_hz: float | None = None

    if sync_row is None:
        flags.append("missing_sync_index_row")
    elif sync_row.get("sync_status") and sync_row.get("sync_status") != "ok":
        flags.append("sync_status_not_ok")
    if slice_row.get("status") and slice_row.get("status") != "ok":
        flags.append("slice_status_not_ok")
    if slice_row.get("sync_quality_flags") and slice_row.get("sync_quality_flags") != "ok":
        flags.append("sync_quality_warning")

    if not csi_out_value or not csi_path.exists():
        quality = DatQuality(parse_status="missing", notes="missing csi slice file")
        flags.append("missing_csi_slice_file")
    elif csi_path.stat().st_size == 0:
        quality = DatQuality(parse_status="empty", file_size_bytes=0, notes="empty csi slice file")
        flags.append("empty_csi_slice_file")
    else:
        quality = read_dat_quality(csi_path, payload_sample_packets=args.payload_sample_packets)
        if quality.packet_count == 0:
            flags.append("no_dat_packets")
        if quality.trailing_partial_packet_count:
            flags.append("trailing_partial_packet")
        if quality.csi_size_mismatch_count:
            flags.append("csi_size_mismatch")
        if quality.bad_csi_size_count:
            flags.append("bad_csi_size")

    dat_packet_count = quality.packet_count if quality.packet_count else None
    if dat_packet_count is not None and action_duration_sec:
        packet_rate_hz = dat_packet_count / action_duration_sec
        flags.extend(classify_packet_rate(dat_packet_count, action_duration_sec, args.packet_rate_low_hz, args.packet_rate_high_hz))
    elif dat_packet_count is None:
        flags.append("missing_packet_rate")

    if dat_packet_count is not None and written_slice is not None and dat_packet_count != written_slice:
        flags.append("packet_count_mismatch_slice_index")
    if dat_packet_count is not None and expected_slice is not None and dat_packet_count != expected_slice:
        flags.append("packet_count_mismatch_slice_expected")
    if dat_packet_count is not None and expected_sync is not None and dat_packet_count != expected_sync:
        flags.append("packet_count_mismatch_sync_index")

    if quality.payload_packets_checked:
        if quality.global_nonzero_ratio == 0.0:
            flags.append("all_zero_csi_payload")
        elif math.isfinite(quality.global_nonzero_ratio) and quality.global_nonzero_ratio < args.low_nonzero_ratio:
            flags.append("low_nonzero_ratio")
        if quality.zero_packet_count:
            flags.append("sampled_zero_packet")
        if quality.dead_link_count:
            flags.append("dead_rx_tx_link")
        if math.isfinite(quality.global_amp_std) and quality.global_amp_std <= args.constant_amp_std:
            flags.append("constant_csi_amplitude")
    else:
        flags.append("payload_not_checked")

    matched_reviews = matching_review_rules(sample_id, review_rules)
    if matched_reviews:
        flags.append("video_review_issue")
        if any("✅" in rule.resample_status or "已补采" in rule.resample_status or "有补采" in rule.resample_status for rule in matched_reviews):
            flags.append("video_review_resampled_available")
        if any("❌" in rule.resample_status or "未补采" in rule.resample_status or "未修正" in rule.resample_status for rule in matched_reviews):
            flags.append("video_review_unresolved")

    if quality.notes:
        notes.append(quality.notes)
    if sync_row and sync_row.get("notes"):
        notes.append(f"sync: {sync_row['notes']}")
    if slice_row.get("notes"):
        notes.append(f"slice: {slice_row['notes']}")

    flags = sorted(set(flags))
    final_status = final_status_from_flags(flags)
    quality_flags = ";".join(flags) if flags else "ok"

    packet_delta_slice = ""
    if dat_packet_count is not None and written_slice is not None:
        packet_delta_slice = dat_packet_count - written_slice
    packet_delta_sync = ""
    if dat_packet_count is not None and expected_sync is not None:
        packet_delta_sync = dat_packet_count - expected_sync

    return {
        "sample_id": sample_id,
        "session_id": slice_row.get("session_id", ""),
        "person_id": slice_row.get("person_id", ""),
        "environment_id": slice_row.get("environment_id", ""),
        "action_id": slice_row.get("action_id", ""),
        "trial_id": slice_row.get("trial_id", ""),
        "csi_out_path": rel(csi_path, root) if csi_out_value else "",
        "csi_in_path": slice_row.get("csi_in_path", ""),
        "sync_status": sync_row.get("sync_status", "") if sync_row else "",
        "sync_quality_flags": slice_row.get("sync_quality_flags", ""),
        "slice_status": slice_row.get("status", ""),
        "csi_index_method": slice_row.get("csi_index_method", ""),
        "expected_packets_slice_index": expected_slice or "",
        "written_packets_slice_index": written_slice or "",
        "expected_packets_sync_index": expected_sync or "",
        "dat_packet_count": dat_packet_count or "",
        "packet_count_delta_slice": packet_delta_slice,
        "packet_count_delta_sync": packet_delta_sync,
        "action_duration_sec": fmt_float(action_duration_sec, 3),
        "packet_rate_hz": fmt_float(packet_rate_hz, 3),
        "file_size_bytes": quality.file_size_bytes,
        "parse_status": quality.parse_status,
        "bad_packet_count": quality.bad_packet_count,
        "trailing_partial_packet_count": quality.trailing_partial_packet_count,
        "csi_size_mismatch_count": quality.csi_size_mismatch_count,
        "bad_csi_size_count": quality.bad_csi_size_count,
        "payload_packets_checked": quality.payload_packets_checked,
        "zero_packet_count": quality.zero_packet_count,
        "num_rx_values": quality.num_rx_values,
        "num_tx_values": quality.num_tx_values,
        "num_subcarrier_values": quality.num_subcarrier_values,
        "global_nonzero_ratio": fmt_float(quality.global_nonzero_ratio, 6),
        "global_amp_min": fmt_float(quality.global_amp_min, 3),
        "global_amp_mean": fmt_float(quality.global_amp_mean, 3),
        "global_amp_std": fmt_float(quality.global_amp_std, 3),
        "global_amp_max": fmt_float(quality.global_amp_max, 3),
        "dead_link_count": quality.dead_link_count,
        "link_nonzero_ratio_min": fmt_float(quality.link_nonzero_ratio_min, 6),
        "link_amp_mean_min": fmt_float(quality.link_amp_mean_min, 3),
        "video_review_issue_count": len(matched_reviews),
        "video_review_categories": ";".join(sorted({rule.category for rule in matched_reviews})),
        "video_review_resample_statuses": ";".join(sorted({rule.resample_status for rule in matched_reviews})),
        "video_review_descriptions": ";".join(sorted({rule.description for rule in matched_reviews})),
        "quality_flags": quality_flags,
        "final_status": final_status,
        "notes": "; ".join(notes),
    }


def numeric_values(rows: list[dict[str, object]], field: str) -> list[float]:
    values = []
    for row in rows:
        value = to_float(row.get(field))
        if value is not None:
            values.append(value)
    return values


def summarize_distribution(rows: list[dict[str, object]], field: str) -> str:
    values = sorted(numeric_values(rows, field))
    if not values:
        return "count=0"
    return (
        f"count={len(values)}, min={values[0]:.3f}, "
        f"p50={percentile(values, 0.50):.3f}, p95={percentile(values, 0.95):.3f}, max={values[-1]:.3f}"
    )


def summarize_numeric_values(values: list[float], target_rate_hz: float | None = None) -> dict[str, float | int]:
    values = sorted(values)
    if not values:
        summary: dict[str, float | int] = {
            "count": 0,
            "min": math.nan,
            "p50": math.nan,
            "p95": math.nan,
            "max": math.nan,
            "mean": math.nan,
            "std": math.nan,
        }
    else:
        mean = sum(values) / len(values)
        variance = sum((value - mean) ** 2 for value in values) / len(values)
        summary = {
            "count": len(values),
            "min": values[0],
            "p50": percentile(values, 0.50),
            "p95": percentile(values, 0.95),
            "max": values[-1],
            "mean": mean,
            "std": math.sqrt(variance),
        }
    if target_rate_hz is not None and math.isfinite(float(summary["mean"])):
        delta = float(summary["mean"]) - target_rate_hz
        summary["mean_delta_from_target"] = delta
        summary["mean_delta_percent_from_target"] = (delta / target_rate_hz * 100.0) if target_rate_hz else math.nan
    else:
        summary["mean_delta_from_target"] = math.nan
        summary["mean_delta_percent_from_target"] = math.nan
    return summary


def has_flag(row: dict[str, object], flag_name: str) -> bool:
    flags = str(row.get("quality_flags", ""))
    return flag_name in {flag for flag in flags.split(";") if flag}


def summarize_packet_rates(rows: list[dict[str, object]], target_rate_hz: float = 100.0) -> dict[str, object]:
    all_rates: list[float] = []
    normal_rates: list[float] = []
    outlier_ids: list[str] = []

    for row in rows:
        rate = to_float(row.get("packet_rate_hz"))
        if rate is None:
            continue
        all_rates.append(rate)
        is_rate_outlier = has_flag(row, "low_packet_rate") or has_flag(row, "high_packet_rate")
        if is_rate_outlier:
            outlier_ids.append(str(row.get("sample_id", "")))
        else:
            normal_rates.append(rate)

    all_summary = summarize_numeric_values(all_rates, target_rate_hz)
    normal_summary = summarize_numeric_values(normal_rates, target_rate_hz)
    return {
        "all_count": all_summary["count"],
        "all_mean": all_summary["mean"],
        "all_std": all_summary["std"],
        "all_min": all_summary["min"],
        "all_p50": all_summary["p50"],
        "all_p95": all_summary["p95"],
        "all_max": all_summary["max"],
        "all_mean_delta_from_target": all_summary["mean_delta_from_target"],
        "all_mean_delta_percent_from_target": all_summary["mean_delta_percent_from_target"],
        "normal_count": normal_summary["count"],
        "normal_mean": normal_summary["mean"],
        "normal_std": normal_summary["std"],
        "normal_min": normal_summary["min"],
        "normal_p50": normal_summary["p50"],
        "normal_p95": normal_summary["p95"],
        "normal_max": normal_summary["max"],
        "normal_mean_delta_from_target": normal_summary["mean_delta_from_target"],
        "normal_mean_delta_percent_from_target": normal_summary["mean_delta_percent_from_target"],
        "rate_outlier_count": len(outlier_ids),
        "rate_outlier_sample_ids": outlier_ids,
    }


def format_rate_summary(summary: dict[str, object], prefix: str) -> str:
    count = int(summary[f"{prefix}_count"])
    if count == 0:
        return "count=0"
    return (
        f"count={count}, mean={float(summary[f'{prefix}_mean']):.3f} Hz, "
        f"std={float(summary[f'{prefix}_std']):.3f}, min={float(summary[f'{prefix}_min']):.3f}, "
        f"p50={float(summary[f'{prefix}_p50']):.3f}, p95={float(summary[f'{prefix}_p95']):.3f}, "
        f"max={float(summary[f'{prefix}_max']):.3f}, "
        f"mean_delta_from_target={float(summary[f'{prefix}_mean_delta_from_target']):+.3f} Hz "
        f"({float(summary[f'{prefix}_mean_delta_percent_from_target']):+.3f}%)"
    )


def percentile(values: list[float], q: float) -> float:
    if not values:
        return math.nan
    if len(values) == 1:
        return values[0]
    pos = (len(values) - 1) * q
    lower = math.floor(pos)
    upper = math.ceil(pos)
    if lower == upper:
        return values[int(pos)]
    weight = pos - lower
    return values[lower] * (1 - weight) + values[upper] * weight


def flag_counts(rows: list[dict[str, object]]) -> Counter[str]:
    counts: Counter[str] = Counter()
    for row in rows:
        flags = str(row.get("quality_flags", ""))
        if flags == "ok":
            counts["ok"] += 1
            continue
        for flag in flags.split(";"):
            if flag:
                counts[flag] += 1
    return counts


def write_summary(
    path: Path,
    root: Path,
    args: argparse.Namespace,
    slice_count: int,
    sync_count: int,
    review_rule_count: int,
    rows: list[dict[str, object]],
    outlier_count: int,
) -> None:
    status_counts = Counter(str(row.get("final_status", "")) for row in rows)
    parse_counts = Counter(str(row.get("parse_status", "")) for row in rows)
    flag_counter = flag_counts(rows)
    action_counts = Counter(str(row.get("action_id", "")) for row in rows)
    packet_rate_summary = summarize_packet_rates(rows, target_rate_hz=args.target_csi_rate_hz)
    category_counts: Counter[str] = Counter()
    resample_counts: Counter[str] = Counter()
    for row in rows:
        for category in str(row.get("video_review_categories", "")).split(";"):
            if category:
                category_counts[category] += 1
        for status in str(row.get("video_review_resample_statuses", "")).split(";"):
            if status:
                resample_counts[status] += 1

    def sum_int(field: str) -> int:
        return sum(to_int(row.get(field)) or 0 for row in rows)

    lines = [
        "# CSI Slice Quality Report",
        "",
        "## Inputs",
        "",
        f"- Project root: `{root}`",
        f"- Slice index: `{args.slice_index}` ({slice_count} rows)",
        f"- Sync index: `{args.sync_index}` ({sync_count} rows)",
        f"- Video review: `{args.video_review or 'skipped'}` ({review_rule_count} parsed rules)",
        f"- Payload sample packets per file: `{args.payload_sample_packets}`",
        f"- Configured CSI sampling rate: `{args.target_csi_rate_hz:.1f}` Hz",
        f"- Packet-rate thresholds: `{args.packet_rate_low_hz:.1f}` to `{args.packet_rate_high_hz:.1f}` Hz",
        "",
        "## Outputs",
        "",
        f"- Quality CSV: `{rel(path.parent / 'csi_slice_quality.csv', root)}`",
        f"- Outlier CSV: `{rel(path.parent / 'csi_outlier_samples.csv', root)}` ({outlier_count} rows)",
        f"- Report: `{rel(path, root)}`",
        "",
        "## Check Scope",
        "",
        f"- Checked sliced CSI windows from `slice_index.csv`: {len(rows)} rows.",
        "- This report validates generated CSI slices, not the raw capture workflow end to end.",
        "- The script reads sliced `.dat` files, the CSI/video sync index, and the manual video review document.",
        "- Raw `.dat`, `.mkv`, timestamp CSV, log, marker, and manifest files are not modified.",
        "- CSI packet ranges use the existing sync/slice indexes; the program does not recut CSI windows.",
        "",
        "## Check Items",
        "",
        "- File existence: missing and empty CSI slice files.",
        "- FeitCSI packet structure: header parse, `csi_size`, RX/TX count, subcarrier count, bad packets, and trailing partial packets.",
        "- Packet-count consistency: actual parsed packet count vs. `slice_index.csv` and `csi_video_sync_index.csv`.",
        "- Packet-rate quality: actual packets divided by action duration, compared with the configured 100 Hz target and the 80-130 Hz warning range.",
        "- Payload signal sanity: sampled CSI payload nonzero ratio, amplitude mean/std/min/max, zero packets, and dead RX/TX links.",
        "- Video review merge: samples in `Video_review.md` are conservatively flagged so they are not treated as clean samples.",
        "",
        "## Status Summary",
        "",
    ]
    for status, count in sorted(status_counts.items()):
        lines.append(f"- `{status}`: {count}")

    lines.extend(["", "## Parse Status", ""])
    for status, count in sorted(parse_counts.items()):
        lines.append(f"- `{status}`: {count}")

    lines.extend(["", "## Quality Flags", ""])
    for flag, count in flag_counter.most_common():
        lines.append(f"- `{flag}`: {count}")

    lines.extend(
        [
            "",
            "## CSI Structure Integrity",
            "",
            f"- Parsed `.dat` slices: {parse_counts.get('ok', 0)} / {len(rows)}",
            f"- Missing CSI slice files: {flag_counter.get('missing_csi_slice_file', 0)}",
            f"- Empty CSI slice files: {flag_counter.get('empty_csi_slice_file', 0)}",
            f"- Bad packet total: {sum_int('bad_packet_count')}",
            f"- Trailing partial packet total: {sum_int('trailing_partial_packet_count')}",
            f"- CSI size mismatch total: {sum_int('csi_size_mismatch_count')}",
            f"- Bad CSI size total: {sum_int('bad_csi_size_count')}",
            f"- Packet-count mismatch vs. slice index: {flag_counter.get('packet_count_mismatch_slice_index', 0)}",
            f"- Packet-count mismatch vs. sync index: {flag_counter.get('packet_count_mismatch_sync_index', 0)}",
        ]
    )

    lines.extend(
        [
            "",
            "## Packet Rate Summary",
            "",
            f"- Configured CSI sampling rate at collection time: `{args.target_csi_rate_hz:.1f}` Hz",
            f"- Warning thresholds used by this checker: `< {args.packet_rate_low_hz:.1f}` Hz or `> {args.packet_rate_high_hz:.1f}` Hz",
            f"- All valid packet-rate rows: {format_rate_summary(packet_rate_summary, 'all')}",
            f"- After excluding only `low_packet_rate` / `high_packet_rate` samples: {format_rate_summary(packet_rate_summary, 'normal')}",
            f"- Rate outliers excluded from the cleaned average: {packet_rate_summary['rate_outlier_count']}",
        ]
    )
    outlier_ids = packet_rate_summary["rate_outlier_sample_ids"]
    if outlier_ids:
        lines.append("- Excluded rate-outlier sample IDs:")
        for sample_id in outlier_ids:
            lines.append(f"  - `{sample_id}`")

    lines.extend(["", "## Key Distributions", ""])
    for field in [
        "dat_packet_count",
        "packet_rate_hz",
        "global_nonzero_ratio",
        "global_amp_mean",
        "global_amp_std",
    ]:
        lines.append(f"- {field}: {summarize_distribution(rows, field)}")

    lines.extend(
        [
            "",
            "## Signal Content Summary",
            "",
            f"- Payload packets sampled per file: {args.payload_sample_packets}",
            f"- Files with sampled zero packets: {flag_counter.get('sampled_zero_packet', 0)}",
            f"- Files with all-zero CSI payload: {flag_counter.get('all_zero_csi_payload', 0)}",
            f"- Files with low nonzero ratio: {flag_counter.get('low_nonzero_ratio', 0)}",
            f"- Files with dead RX/TX link: {flag_counter.get('dead_rx_tx_link', 0)}",
            f"- Files with near-constant amplitude: {flag_counter.get('constant_csi_amplitude', 0)}",
            f"- Nonzero ratio distribution: {summarize_distribution(rows, 'global_nonzero_ratio')}",
            f"- Amplitude mean distribution: {summarize_distribution(rows, 'global_amp_mean')}",
            f"- Amplitude std distribution: {summarize_distribution(rows, 'global_amp_std')}",
        ]
    )

    lines.extend(["", "## Video Review Merge", ""])
    lines.append(f"- Samples matched from `Video_review.md`: {flag_counter.get('video_review_issue', 0)}")
    lines.append(f"- Matched samples still unresolved: {flag_counter.get('video_review_unresolved', 0)}")
    lines.append(f"- Matched samples with resampled replacement available: {flag_counter.get('video_review_resampled_available', 0)}")
    if category_counts:
        lines.append("- Video issue categories after range expansion:")
        for category, count in category_counts.most_common():
            lines.append(f"  - `{category}`: {count}")
    if resample_counts:
        lines.append("- Video review resample statuses after range expansion:")
        for status, count in resample_counts.most_common():
            lines.append(f"  - `{status}`: {count}")

    lines.extend(["", "## Actions", ""])
    for action, count in action_counts.most_common():
        lines.append(f"- `{action}`: {count}")

    lines.extend(
        [
            "",
            "## Final Packet Rate Conclusion",
            "",
            f"- Target CSI sampling rate: `{args.target_csi_rate_hz:.1f}` Hz",
            f"- Cleaned mean packet rate after excluding the {packet_rate_summary['rate_outlier_count']} rate-outlier samples: `{float(packet_rate_summary['normal_mean']):.3f}` Hz",
            f"- Difference from target: `{float(packet_rate_summary['normal_mean_delta_from_target']):+.3f}` Hz "
            f"(`{float(packet_rate_summary['normal_mean_delta_percent_from_target']):+.3f}%`)",
            "- This cleaned mean excludes only packet-rate outliers; video-review issues remain included unless their packet rate is also an outlier.",
        ]
    )

    lines.extend(
        [
            "",
            "## Notes",
            "",
            "- Original `.dat`, `.mkv`, timestamp CSV, log, marker, and manifest files were not modified.",
            "- `action_start/action_end` are treated as capture-script cue times, not manually verified motion boundaries.",
            "- Payload signal statistics are sampled per file; header and packet counts are scanned across the whole sliced `.dat`.",
            "- Samples listed in `Video_review.md` are conservatively marked as `video_review_issue` and `final_status=exclude` for the affected original sample IDs.",
        ]
    )

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def progress(enabled: bool, message: str) -> None:
    if not enabled:
        return
    width = 120
    sys.stderr.write("\r" + message[:width].ljust(width))
    sys.stderr.flush()


def progress_done(enabled: bool) -> None:
    if enabled:
        sys.stderr.write("\n")
        sys.stderr.flush()


def format_bar(done: int, total: int) -> str:
    width = 28
    ratio = done / total if total else 1.0
    filled = int(round(width * ratio))
    return "[" + "#" * filled + "-" * (width - filled) + f"] {ratio * 100:5.1f}%"


def main() -> None:
    args = parse_args()
    root = Path(args.project_root).resolve()
    slice_index = resolve_path(root, args.slice_index)
    sync_index = resolve_path(root, args.sync_index)
    output_dir = resolve_path(root, args.output_dir)

    slice_rows = read_csv(slice_index)
    sync_rows = read_csv(sync_index)
    sync_by_sample_id = {row.get("sample_id", ""): row for row in sync_rows if row.get("sample_id")}

    review_rules: list[VideoReviewRule] = []
    if args.video_review:
        review_path = resolve_path(root, args.video_review)
        if review_path.exists():
            review_rules = parse_video_review_rules(review_path.read_text(encoding="utf-8"))

    selected = select_rows(slice_rows, args)
    quality_rows: list[dict[str, object]] = []
    for idx, slice_row in enumerate(selected, start=1):
        sample_id = slice_row.get("sample_id", "")
        progress(
            not args.quiet,
            f"{format_bar(idx, len(selected))} checking {idx}/{len(selected)} {sample_id}",
        )
        quality_rows.append(
            build_quality_row(root, slice_row, sync_by_sample_id.get(sample_id), review_rules, args)
        )
    progress_done(not args.quiet)

    quality_csv = output_dir / "csi_slice_quality.csv"
    outlier_csv = output_dir / "csi_outlier_samples.csv"
    report_md = output_dir / "csi_slice_quality_summary.md"
    outliers = [row for row in quality_rows if row.get("final_status") != "ok"]

    write_csv(quality_csv, quality_rows, OUT_FIELDS)
    write_csv(outlier_csv, outliers, OUTLIER_FIELDS)
    write_summary(
        report_md,
        root,
        args,
        slice_count=len(slice_rows),
        sync_count=len(sync_rows),
        review_rule_count=len(review_rules),
        rows=quality_rows,
        outlier_count=len(outliers),
    )

    status_counts = Counter(str(row.get("final_status", "")) for row in quality_rows)
    print(f"processed samples: {len(quality_rows)}")
    for status, count in sorted(status_counts.items()):
        print(f"{status}: {count}")
    print(f"quality csv: {rel(quality_csv, root)}")
    print(f"outlier csv: {rel(outlier_csv, root)}")
    print(f"report: {rel(report_md, root)}")


if __name__ == "__main__":
    main()
