#!/usr/bin/env python3
"""Slice synchronized CSI .dat packets and video frames from the sync index."""

from __future__ import annotations

import argparse
import csv
import json
import math
import subprocess
import struct
import sys
import time
from collections import Counter
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path


OUT_FIELDS = [
    "sample_id",
    "session_id",
    "person_id",
    "environment_id",
    "action_id",
    "trial_id",
    "sync_quality_flags",
    "csi_index_method",
    "output_group",
    "csi_in_path",
    "csi_out_path",
    "csi_packet_start_idx",
    "csi_packet_end_idx",
    "csi_packets_expected",
    "csi_packets_written",
    "video_in_path",
    "video_out_path",
    "frame_start_idx_raw",
    "frame_end_idx_raw",
    "frame_start_idx_padded",
    "frame_end_idx_padded",
    "video_frames_expected",
    "video_frames_written",
    "video_fps",
    "status",
    "notes",
]


DEFAULT_PREVIEW_ACTIONS = ["walk", "sit_down", "fall_like"]


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Slice CSI action-window .dat files and matching video clips from csi_video_sync_index.csv."
    )
    parser.add_argument("--project-root", default=".", help="Repository/data root.")
    parser.add_argument(
        "--sync-index",
        default="quality_report_deep/csi_video_sync_index/csi_video_sync_index.csv",
        help="CSV generated by data_processing/build_csi_video_sync_index.py.",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Output directory. Defaults to sliced_windows_preview or sliced_windows for --full.",
    )
    parser.add_argument(
        "--group-by-session",
        action="store_true",
        help="Place outputs under <output-dir>/<session_id>/csi|video|metadata instead of grouping only by action.",
    )
    parser.add_argument("--full", action="store_true", help="Process all selected rows. Without this, default is 3 preview samples.")
    parser.add_argument("--limit", type=int, default=None, help="Maximum number of selected samples to process.")
    parser.add_argument("--sample-id", action="append", default=[], help="Specific sample_id to slice. Can be repeated.")
    parser.add_argument("--sample-id-file", default=None, help="Text file with one sample_id per line.")
    parser.add_argument("--session", action="append", default=[], help="Filter by session_id. Can be repeated.")
    parser.add_argument("--action", action="append", default=[], help="Filter by action_id. Can be repeated.")
    parser.add_argument("--list-sessions", action="store_true", help="List available session_id counts from the sync index and exit.")
    parser.add_argument("--include-warn", action="store_true", help="Include rows whose quality_flags are not ok.")
    parser.add_argument(
        "--video-override",
        action="append",
        default=[],
        help="Override video path for a session, formatted as SESSION=path/to/video.mkv. Can be repeated.",
    )
    parser.add_argument("--skip-csi", action="store_true", help="Do not write CSI .dat slices.")
    parser.add_argument("--skip-video", action="store_true", help="Do not write video .mp4 slices.")
    parser.add_argument(
        "--video-writer",
        choices=["ffmpeg", "opencv"],
        default="ffmpeg",
        help="Video slicing backend. Default ffmpeg writes lossless/high-quality clips; opencv keeps legacy mp4v output.",
    )
    parser.add_argument("--ffmpeg-bin", default="ffmpeg", help="ffmpeg executable used when --video-writer=ffmpeg.")
    parser.add_argument(
        "--ffmpeg-crf",
        type=int,
        default=0,
        help="libx264 CRF for ffmpeg slices. 0 is lossless; 18 is visually high quality with smaller files.",
    )
    parser.add_argument("--ffmpeg-preset", default="slow", help="libx264 preset for ffmpeg video slices.")
    parser.add_argument("--ffmpeg-pix-fmt", default="yuv420p", help="Pixel format for ffmpeg video slices.")
    parser.add_argument("--pre-pad-sec", type=float, default=0.0, help="Video-only padding before raw action frame range.")
    parser.add_argument("--post-pad-sec", type=float, default=0.0, help="Video-only padding after raw action frame range.")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite existing generated slices.")
    parser.add_argument(
        "--workers",
        type=int,
        default=1,
        help="Number of samples to process in parallel. Use 1 for deterministic sequential processing.",
    )
    parser.add_argument(
        "--merge-index",
        action="store_true",
        help="Merge this run into an existing <output-dir>/slice_index.csv by sample_id instead of replacing it.",
    )
    parser.add_argument("--quiet", action="store_true", help="Disable terminal progress output.")
    return parser.parse_args(argv)


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def write_csv(path: Path, rows: list[dict[str, object]], fields: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, "") for field in fields})


def merge_rows_by_sample_id(
    existing_rows: list[dict[str, str]],
    new_rows: list[dict[str, object]],
) -> list[dict[str, object]]:
    new_by_sample_id = {str(row.get("sample_id", "")): row for row in new_rows if row.get("sample_id")}
    merged: list[dict[str, object]] = []
    seen: set[str] = set()

    for row in existing_rows:
        sample_id = str(row.get("sample_id", ""))
        if sample_id in new_by_sample_id:
            merged.append(new_by_sample_id[sample_id])
            seen.add(sample_id)
        else:
            merged.append(row)

    for row in new_rows:
        sample_id = str(row.get("sample_id", ""))
        if sample_id and sample_id not in seen:
            merged.append(row)
            seen.add(sample_id)

    return merged


def to_int(value: object) -> int | None:
    try:
        if value is None or value == "":
            return None
        return int(float(str(value)))
    except ValueError:
        return None


def to_float(value: object) -> float | None:
    try:
        if value is None or value == "":
            return None
        number = float(str(value))
    except ValueError:
        return None
    return number if math.isfinite(number) else None


def rel(path: Path | None, root: Path) -> str:
    if path is None:
        return ""
    try:
        return str(path.resolve().relative_to(root.resolve()))
    except ValueError:
        return str(path)


def resolve_path(root: Path, path_value: str) -> Path | None:
    if not path_value:
        return None
    path = Path(path_value)
    if not path.is_absolute():
        path = root / path
    return path if path.exists() else None


def load_sample_ids(path: str | None) -> set[str]:
    ids: set[str] = set()
    if not path:
        return ids
    with Path(path).open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#"):
                ids.add(line)
    return ids


def parse_video_overrides(values: list[str], root: Path) -> dict[str, Path]:
    overrides: dict[str, Path] = {}
    for value in values:
        if "=" not in value:
            raise SystemExit(f"Invalid --video-override value: {value}. Expected SESSION=path")
        session, path_value = value.split("=", 1)
        session = session.strip()
        if not session:
            raise SystemExit(f"Invalid --video-override value: {value}. Empty session")
        path = Path(path_value.strip())
        if not path.is_absolute():
            path = root / path
        if not path.exists():
            raise SystemExit(f"Override video does not exist for {session}: {path}")
        overrides[session] = path
    return overrides


def select_rows(rows: list[dict[str, str]], args: argparse.Namespace) -> list[dict[str, str]]:
    sample_ids = set(args.sample_id)
    sample_ids.update(load_sample_ids(args.sample_id_file))
    sessions = set(args.session)
    actions = set(args.action)

    filtered = []
    for row in rows:
        if sample_ids and row.get("sample_id") not in sample_ids:
            continue
        if sessions and row.get("session_id") not in sessions:
            continue
        if actions and row.get("action_id") not in actions:
            continue
        if not args.include_warn and row.get("quality_flags") != "ok":
            continue
        filtered.append(row)

    if not args.full and not sample_ids:
        preview = []
        seen_actions: set[str] = set()
        for wanted in DEFAULT_PREVIEW_ACTIONS:
            for row in filtered:
                if row.get("action_id") == wanted and wanted not in seen_actions:
                    preview.append(row)
                    seen_actions.add(wanted)
                    break
        if len(preview) < 3:
            for row in filtered:
                if row not in preview and row.get("action_id") != "background_idle":
                    preview.append(row)
                if len(preview) >= 3:
                    break
        filtered = preview

    limit = args.limit
    if limit is None and not args.full:
        limit = 3
    if limit is not None:
        filtered = filtered[:limit]
    return filtered


def list_sessions(rows: list[dict[str, str]], include_warn: bool) -> None:
    counts: Counter[str] = Counter()
    warn_counts: Counter[str] = Counter()
    for row in rows:
        session = row.get("session_id", "")
        if not session:
            continue
        if row.get("quality_flags") == "ok":
            counts[session] += 1
        else:
            warn_counts[session] += 1
            if include_warn:
                counts[session] += 1

    print("session_id,selected_count,warn_count")
    for session in sorted(set(counts) | set(warn_counts)):
        print(f"{session},{counts.get(session, 0)},{warn_counts.get(session, 0)}")


def ensure_output(path: Path, overwrite: bool) -> tuple[bool, str]:
    if path.exists() and not overwrite:
        return False, "exists"
    path.parent.mkdir(parents=True, exist_ok=True)
    return True, ""


def slice_csi_dat(in_path: Path, out_path: Path, start_idx: int, end_idx: int, overwrite: bool) -> tuple[int, str]:
    should_write, reason = ensure_output(out_path, overwrite)
    expected = end_idx - start_idx + 1
    if not should_write:
        return 0, f"skip_csi_{reason}"
    if start_idx < 0 or end_idx < start_idx:
        return 0, "invalid_csi_range"

    written = 0
    with in_path.open("rb") as src, out_path.open("wb") as dst:
        packet_idx = 0
        while packet_idx <= end_idx:
            header = src.read(272)
            if len(header) < 272:
                break
            csi_size = struct.unpack_from("<I", header, 0)[0]
            if csi_size <= 0:
                break
            payload = src.read(csi_size)
            if len(payload) < csi_size:
                break
            if start_idx <= packet_idx <= end_idx:
                dst.write(header)
                dst.write(payload)
                written += 1
            packet_idx += 1

    if written != expected:
        return written, f"csi_written_{written}_expected_{expected}"
    return written, "ok"


def video_padding_frames(row: dict[str, str], pre_pad_sec: float, post_pad_sec: float) -> tuple[int, int, float]:
    fps = to_float(row.get("video_effective_fps")) or 30.0
    pre = max(0, int(round(pre_pad_sec * fps)))
    post = max(0, int(round(post_pad_sec * fps)))
    return pre, post, fps


def build_ffmpeg_video_slice_command(
    in_path: Path,
    out_path: Path,
    start_idx: int,
    end_idx: int,
    crf: int,
    preset: str,
    pix_fmt: str,
    ffmpeg_bin: str = "ffmpeg",
) -> list[str]:
    frame_filter = f"select=between(n\\,{start_idx}\\,{end_idx}),setpts=N/FRAME_RATE/TB"
    return [
        ffmpeg_bin,
        "-hide_banner",
        "-loglevel",
        "error",
        "-y",
        "-i",
        str(in_path),
        "-vf",
        frame_filter,
        "-an",
        "-c:v",
        "libx264",
        "-preset",
        preset,
        "-crf",
        str(crf),
        "-pix_fmt",
        pix_fmt,
        str(out_path),
    ]


def slice_video_ffmpeg(
    in_path: Path,
    out_path: Path,
    start_idx: int,
    end_idx: int,
    fps_hint: float,
    overwrite: bool,
    ffmpeg_bin: str,
    crf: int,
    preset: str,
    pix_fmt: str,
) -> tuple[int, str, float]:
    should_write, reason = ensure_output(out_path, overwrite)
    expected = end_idx - start_idx + 1
    if not should_write:
        return 0, f"skip_video_{reason}", fps_hint
    if start_idx < 0 or end_idx < start_idx:
        return 0, "invalid_video_range", fps_hint

    cmd = build_ffmpeg_video_slice_command(
        in_path,
        out_path,
        start_idx,
        end_idx,
        crf=crf,
        preset=preset,
        pix_fmt=pix_fmt,
        ffmpeg_bin=ffmpeg_bin,
    )
    try:
        completed = subprocess.run(cmd, check=False, capture_output=True, text=True)
    except FileNotFoundError as exc:
        return 0, f"ffmpeg_missing:{exc}", fps_hint

    if completed.returncode != 0:
        try:
            out_path.unlink()
        except FileNotFoundError:
            pass
        message = completed.stderr.strip().replace("\n", " ")[:240]
        return 0, f"ffmpeg_failed:{message}", fps_hint
    return expected, "ok", fps_hint


def slice_video_opencv(
    in_path: Path,
    out_path: Path,
    start_idx: int,
    end_idx: int,
    fps_hint: float,
    overwrite: bool,
) -> tuple[int, str, float]:
    should_write, reason = ensure_output(out_path, overwrite)
    expected = end_idx - start_idx + 1
    if not should_write:
        return 0, f"skip_video_{reason}", fps_hint
    if start_idx < 0 or end_idx < start_idx:
        return 0, "invalid_video_range", fps_hint

    try:
        import cv2
    except ImportError as exc:
        return 0, f"opencv_missing:{exc}", fps_hint

    cap = cv2.VideoCapture(str(in_path))
    if not cap.isOpened():
        return 0, "video_open_failed", fps_hint

    fps = cap.get(cv2.CAP_PROP_FPS)
    if not fps or not math.isfinite(fps) or fps <= 0:
        fps = fps_hint if fps_hint > 0 else 30.0
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    if width <= 0 or height <= 0:
        cap.release()
        return 0, "invalid_video_dimensions", fps

    writer = cv2.VideoWriter(str(out_path), cv2.VideoWriter_fourcc(*"mp4v"), fps, (width, height))
    if not writer.isOpened():
        cap.release()
        return 0, "video_writer_open_failed", fps

    cap.set(cv2.CAP_PROP_POS_FRAMES, start_idx)
    pos_after_seek = cap.get(cv2.CAP_PROP_POS_FRAMES)
    if start_idx > 0 and pos_after_seek < max(0, start_idx - 1):
        writer.release()
        cap.release()
        try:
            out_path.unlink()
        except FileNotFoundError:
            pass
        return 0, f"video_seek_failed_pos_{pos_after_seek:.0f}_target_{start_idx}", fps

    written = 0
    for _frame_idx in range(start_idx, end_idx + 1):
        ok, frame = cap.read()
        if not ok:
            break
        writer.write(frame)
        written += 1

    writer.release()
    cap.release()

    if written != expected:
        return written, f"video_written_{written}_expected_{expected}", fps
    return written, "ok", fps


def slice_video(
    in_path: Path,
    out_path: Path,
    start_idx: int,
    end_idx: int,
    fps_hint: float,
    overwrite: bool,
    args: argparse.Namespace,
) -> tuple[int, str, float]:
    if args.video_writer == "opencv":
        return slice_video_opencv(in_path, out_path, start_idx, end_idx, fps_hint, overwrite)
    return slice_video_ffmpeg(
        in_path,
        out_path,
        start_idx,
        end_idx,
        fps_hint,
        overwrite,
        args.ffmpeg_bin,
        args.ffmpeg_crf,
        args.ffmpeg_preset,
        args.ffmpeg_pix_fmt,
    )


def write_metadata(path: Path, row: dict[str, str], result: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "source_sync_row": row,
        "slice_result": result,
    }
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def row_output_root(out_root: Path, row: dict[str, str], args: argparse.Namespace) -> Path:
    if args.group_by_session:
        session = row.get("session_id", "unknown") or "unknown"
        return out_root / session
    return out_root


def progress_line(enabled: bool, message: str) -> None:
    if not enabled:
        return
    width = 120
    sys.stderr.write("\r" + message[:width].ljust(width))
    sys.stderr.flush()


def format_progress_bar(current: int, total: int, width: int = 28) -> str:
    if total <= 0:
        return "[" + "-" * width + "]"
    ratio = max(0.0, min(1.0, current / total))
    filled = int(round(ratio * width))
    return "[" + "#" * filled + "-" * (width - filled) + f"] {ratio * 100:5.1f}%"


def progress_done(enabled: bool) -> None:
    if enabled:
        sys.stderr.write("\n")
        sys.stderr.flush()


def process_row_task(payload: tuple[Path, Path, dict[str, str], argparse.Namespace]) -> dict[str, object]:
    root, out_root, row, args = payload
    return process_row(root, out_root, row, args)


def process_rows(
    root: Path,
    out_root: Path,
    selected: list[dict[str, str]],
    args: argparse.Namespace,
    process_one=None,
) -> list[dict[str, object]]:
    if process_one is None:
        process_one = process_row
    workers = max(1, int(args.workers or 1))
    show_progress = not args.quiet
    total = len(selected)
    started = time.time()

    if workers == 1 or process_one is not process_row:
        results = []
        for idx, row in enumerate(selected, start=1):
            sample_id = row.get("sample_id", "")
            action = row.get("action_id", "")
            elapsed = time.time() - started
            avg = elapsed / max(1, idx - 1) if idx > 1 else 0.0
            remaining = avg * (total - idx + 1) if idx > 1 else 0.0
            bar = format_progress_bar(idx - 1, total)
            progress_line(
                show_progress,
                f"{bar} {idx}/{total} running {sample_id} action={action} elapsed={elapsed:.1f}s eta={remaining:.1f}s workers={workers}",
            )
            results.append(process_one(root, out_root, row, args))
            elapsed = time.time() - started
            avg = elapsed / idx
            remaining = avg * (total - idx)
            bar = format_progress_bar(idx, total)
            progress_line(
                show_progress,
                f"{bar} {idx}/{total} done {sample_id} status={results[-1].get('status')} elapsed={elapsed:.1f}s eta={remaining:.1f}s workers={workers}",
            )
        progress_done(show_progress)
        return results

    results: list[dict[str, object] | None] = [None] * total
    with ProcessPoolExecutor(max_workers=workers) as executor:
        futures = {
            executor.submit(process_row_task, (root, out_root, row, args)): idx
            for idx, row in enumerate(selected)
        }
        completed_count = 0
        for future in as_completed(futures):
            idx = futures[future]
            results[idx] = future.result()
            completed_count += 1
            elapsed = time.time() - started
            avg = elapsed / completed_count
            remaining = avg * (total - completed_count)
            sample_id = selected[idx].get("sample_id", "")
            bar = format_progress_bar(completed_count, total)
            progress_line(
                show_progress,
                f"{bar} {completed_count}/{total} done {sample_id} status={results[idx].get('status')} elapsed={elapsed:.1f}s eta={remaining:.1f}s workers={workers}",
            )
    progress_done(show_progress)
    return [row for row in results if row is not None]


def process_row(root: Path, out_root: Path, row: dict[str, str], args: argparse.Namespace) -> dict[str, object]:
    sample_id = row["sample_id"]
    action = row.get("action_id", "unknown") or "unknown"
    csi_in = resolve_path(root, row.get("csi_path", ""))
    video_overrides = getattr(args, "_video_overrides", {})
    video_in = video_overrides.get(row.get("session_id", "")) or resolve_path(root, row.get("video_path", ""))

    csi_start = to_int(row.get("csi_packet_start_idx"))
    csi_end = to_int(row.get("csi_packet_end_idx"))
    frame_start = to_int(row.get("frame_start_idx_raw"))
    frame_end = to_int(row.get("frame_end_idx_raw"))
    total_frames = to_int(row.get("video_frame_count_total"))

    pre_frames, post_frames, fps_hint = video_padding_frames(row, args.pre_pad_sec, args.post_pad_sec)
    frame_start_padded = max(0, (frame_start or 0) - pre_frames) if frame_start is not None else None
    frame_end_padded = (frame_end or 0) + post_frames if frame_end is not None else None
    if frame_end_padded is not None and total_frames is not None:
        frame_end_padded = min(total_frames - 1, frame_end_padded)

    sample_root = row_output_root(out_root, row, args)
    csi_out = sample_root / "csi" / action / f"{sample_id}.dat"
    video_out = sample_root / "video" / action / f"{sample_id}.mp4"
    meta_out = sample_root / "metadata" / action / f"{sample_id}.json"

    notes: list[str] = []
    status_parts: list[str] = []
    csi_written = ""
    video_written = ""
    actual_fps = fps_hint

    if args.skip_csi:
        status_parts.append("csi_skipped")
    elif csi_in is None:
        status_parts.append("csi_missing")
    elif csi_start is None or csi_end is None:
        status_parts.append("csi_range_missing")
    else:
        csi_written_i, note = slice_csi_dat(csi_in, csi_out, csi_start, csi_end, args.overwrite)
        csi_written = csi_written_i
        status_parts.append(f"csi_{note}")
        if note != "ok":
            notes.append(note)

    if args.skip_video:
        status_parts.append("video_skipped")
    elif video_in is None:
        status_parts.append("video_missing")
    elif frame_start_padded is None or frame_end_padded is None:
        status_parts.append("video_range_missing")
    else:
        video_written_i, note, actual_fps = slice_video(
            video_in,
            video_out,
            frame_start_padded,
            frame_end_padded,
            fps_hint,
            args.overwrite,
            args,
        )
        video_written = video_written_i
        status_parts.append(f"video_{note}")
        if note != "ok":
            notes.append(note)

    status = "ok" if all(part.endswith("_ok") or part.endswith("_skipped") for part in status_parts) else "warn"

    result = {
        "sample_id": sample_id,
        "session_id": row.get("session_id", ""),
        "person_id": row.get("person_id", ""),
        "environment_id": row.get("environment_id", ""),
        "action_id": action,
        "trial_id": row.get("trial_id", ""),
        "sync_quality_flags": row.get("quality_flags", ""),
        "csi_index_method": row.get("csi_index_method", ""),
        "output_group": rel(sample_root, root),
        "csi_in_path": rel(csi_in, root),
        "csi_out_path": rel(csi_out, root) if not args.skip_csi else "",
        "csi_packet_start_idx": csi_start if csi_start is not None else "",
        "csi_packet_end_idx": csi_end if csi_end is not None else "",
        "csi_packets_expected": (csi_end - csi_start + 1) if csi_start is not None and csi_end is not None else "",
        "csi_packets_written": csi_written,
        "video_in_path": rel(video_in, root),
        "video_out_path": rel(video_out, root) if not args.skip_video else "",
        "frame_start_idx_raw": frame_start if frame_start is not None else "",
        "frame_end_idx_raw": frame_end if frame_end is not None else "",
        "frame_start_idx_padded": frame_start_padded if frame_start_padded is not None else "",
        "frame_end_idx_padded": frame_end_padded if frame_end_padded is not None else "",
        "video_frames_expected": (frame_end_padded - frame_start_padded + 1)
        if frame_start_padded is not None and frame_end_padded is not None
        else "",
        "video_frames_written": video_written,
        "video_fps": f"{actual_fps:.3f}" if actual_fps else "",
        "status": status,
        "notes": ";".join(notes),
    }
    write_metadata(meta_out, row, result)
    return result


def write_report(path: Path, rows: list[dict[str, object]], args: argparse.Namespace) -> None:
    status_counts = Counter(str(row.get("status", "")) for row in rows)
    action_counts = Counter(str(row.get("action_id", "")) for row in rows)
    lines = [
        "# CSI/Video Slice Report",
        "",
        "## Command Mode",
        "",
        f"- full: `{args.full}`",
        f"- include_warn: `{args.include_warn}`",
        f"- pre_pad_sec: `{args.pre_pad_sec}`",
        f"- post_pad_sec: `{args.post_pad_sec}`",
        f"- skip_csi: `{args.skip_csi}`",
        f"- skip_video: `{args.skip_video}`",
        f"- video_writer: `{args.video_writer}`",
        f"- ffmpeg_crf: `{args.ffmpeg_crf}`",
        f"- ffmpeg_preset: `{args.ffmpeg_preset}`",
        f"- ffmpeg_pix_fmt: `{args.ffmpeg_pix_fmt}`",
        f"- workers: `{args.workers}`",
        f"- group_by_session: `{args.group_by_session}`",
        f"- merge_index: `{args.merge_index}`",
        "",
        "## Summary",
        "",
        f"- processed samples: {len(rows)}",
    ]
    for status, count in status_counts.most_common():
        lines.append(f"- `{status}`: {count}")
    lines.extend(["", "## Actions", ""])
    for action, count in action_counts.most_common():
        lines.append(f"- `{action}`: {count}")
    lines.extend(
        [
            "",
            "## Notes",
            "",
            "- Original `.dat`, `.mkv`, timestamp CSV, log, marker, and manifest files were not modified.",
            "- CSI slices are packet-preserving `.dat` subsets.",
            "- Video slices are written by frame index from the synchronization index.",
            "- Default video slicing uses ffmpeg/libx264 CRF 0 lossless output to avoid the legacy OpenCV mp4v low-bitrate compression.",
            "- Review preview clips before running full dataset slicing.",
        ]
    )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    root = Path(args.project_root).resolve()
    args._video_overrides = parse_video_overrides(args.video_override, root)
    sync_index = (root / args.sync_index).resolve()
    out_root = Path(args.output_dir) if args.output_dir else Path("sliced_windows" if args.full else "sliced_windows_preview")
    if not out_root.is_absolute():
        out_root = root / out_root

    rows = read_csv(sync_index)
    if args.list_sessions:
        list_sessions(rows, args.include_warn)
        return

    selected = select_rows(rows, args)
    if not selected:
        raise SystemExit("No rows selected. Check filters or use --include-warn.")

    results = process_rows(root, out_root, selected, args)

    slice_index = out_root / "slice_index.csv"
    report = out_root / "slice_report.md"
    index_rows: list[dict[str, object]] = results
    if args.merge_index and slice_index.exists():
        index_rows = merge_rows_by_sample_id(read_csv(slice_index), results)
    write_csv(slice_index, index_rows, OUT_FIELDS)
    write_report(report, index_rows, args)

    if args.group_by_session:
        by_session: dict[str, list[dict[str, object]]] = {}
        for row in results:
            session = str(row.get("session_id", "unknown") or "unknown")
            by_session.setdefault(session, []).append(row)
        for session, session_rows in sorted(by_session.items()):
            session_root = out_root / session
            write_csv(session_root / "slice_index.csv", session_rows, OUT_FIELDS)
            write_report(session_root / "slice_report.md", session_rows, args)

    counts = Counter(str(row["status"]) for row in results)
    print(f"processed={len(results)} output_dir={out_root}")
    print(f"slice_index={slice_index}")
    print(f"report={report}")
    print("status=" + ", ".join(f"{k}:{v}" for k, v in counts.most_common()))


if __name__ == "__main__":
    main()
